cask_args appdir: '/Applications'

tap 'homebrew/bundle'
# tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
# brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'spark'
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'vim'
brew 'zsh'


cask '1password'
cask 'adium'
cask 'adobe-acrobat'
cask 'alfred'
cask 'anaconda'
cask 'Boxcryptor'
cask 'box-sync'
cask 'evernote'
cask 'eclipse-installer'
# cask 'fantastical'   get from app store instead
cask 'firefox'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'java'
cask 'jetbrains-toolbox'
cask 'kaleidoscope'
cask 'netbeans-java-se'
cask 'omnifocus'
cask 'omnigraffle'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'tower'
cask 'transmission'
cask 'resilio-sync'
cask 'sequel-pro'
cask 'sizeup'
cask 'unity-download-assistant'

