alias mpgov='export AWS_PROFILE=mp-gov'
alias eccogov='export AWS_PROFILE=ecco-gov'
alias movesgov='export AWS_PROFILE=lincolnlabs-ops'
alias eccocomw1='export AWS_PROFILE=nps-ops-w1'
alias eccocomw2='export AWS_PROFILE=nps-ops-w2'
alias perscom='export AWS_PROFILE=zenuevo-admin'
alias west1='export AWS_REGION=us-west-1'
alias west2='export AWS_REGION=us-west-2'
alias east1='export AWS_REGION=us-east-1'
alias govwest='export AWS_REGION=us-gov-west-1'

